### ISSUE TITLE
VC++版本的ExerciseBook的2.12.c中的判断条件有误

### ISSUE THREAD

**Issue by Zam-0703** [kangjianwei/Data-Structure#13]
02.12.c文件的Line 44处，判断条件应改成`mark == 1`

**Comment by kangjianwei** [comment]
@Zam-0703 我看了下，先写了小于跟大于，第三种情况就是等于啊...感觉没问题啊...可否再详细说明？

**Comment by Zam-0703** [comment]
emmm你Algo_2_12函数当A>B的时候返回值是1，然而你这里写的判断条件是mark>1
________________________________

**Comment by kangjianwei** [comment]
@Zam-0703 嗯，已经修正了，应该是大于0！
