### ISSUE TITLE
是否可以在VsCode下运行？

### ISSUE THREAD

**Issue by yuleiQ** [kangjianwei/Data-Structure#14]
你好，我使用vscode配置C语言环境可以使用您文件夹中的代码么？

**Comment by yuleiQ** [comment]
> 你好，我使用vscode配置C语言环境可以使用您文件夹中的代码么？

好心塞 用vscode执行不出来

**Comment by kangjianwei** [comment]
@yuleiQ 理论上是可以的。先配置cmake环境，再到VsCode中使用CLion分支下的代码。具体操作去网上搜一下教程。

**Comment by yuleiQ** [comment]
谢谢 我尝试下
