### ISSUE TITLE
请问下我用clion,环境配置好了，但是运行带main的文件报错？

### ISSUE THREAD

**Issue by pingyuan2016** [kangjianwei/Data-Structure#21]
请问这是什么问题？新手一个
<img width="993" alt="微信截图_20200428222750" src="https://user-images.githubusercontent.com/25808622/80499566-bb18ee00-899f-11ea-9a87-fe2b21cd5ced.png">
<img width="727" alt="微信截图_20200428222816" src="https://user-images.githubusercontent.com/25808622/80499574-bce2b180-899f-11ea-8e75-2bf8da11a559.png">

**Comment by kangjianwei** [comment]
@pingyuan2016 这是编码问题。我在README中提到，CLion版本的代码使用了UTF编码。你这个编码可能是用了GBK，所以无法识别。打开设置，在Editor-->FIle Encoding中将编码都设置为UTF-8，然后重新导入项目。
