### ISSUE TITLE
习题2.4和习题2.7

### ISSUE THREAD

**Issue by CaiCandong** [kangjianwei/Data-Structure#22]
[习题解析2-4](https://github.com/kangjianwei/Data-Structure/blob/master/%E4%B9%A0%E9%A2%98%E8%A7%A3%E6%9E%90/02%20%E7%BA%BF%E6%80%A7%E8%A1%A8/%E7%AC%AC02%E7%AB%A0%20%E7%BA%BF%E6%80%A7%E8%A1%A8.md#24-%E5%AF%B9%E4%BB%A5%E4%B8%8B%E5%8D%95%E9%93%BE%E8%A1%A8%E5%88%86%E5%88%AB%E6%89%A7%E8%A1%8C%E4%B8%8B%E5%88%97%E5%90%84%E7%A8%8B%E5%BA%8F%E6%AE%B5%E5%B9%B6%E7%94%BB%E5%87%BA%E7%BB%93%E6%9E%9C%E7%A4%BA%E6%84%8F%E5%9B%BE)
（6）（7）两问的在最后一个元素的区别没有体现出来

**Comment by CaiCandong** [comment]
[习题解析2-7-b](https://github.com/kangjianwei/Data-Structure/blob/master/%E4%B9%A0%E9%A2%98%E8%A7%A3%E6%9E%90/02%20%E7%BA%BF%E6%80%A7%E8%A1%A8/%E7%AC%AC02%E7%AB%A0%20%E7%BA%BF%E6%80%A7%E8%A1%A8.md#27-%E5%B7%B2%E7%9F%A5l%E6%98%AF%E5%B8%A6%E8%A1%A8%E5%A4%B4%E7%BB%93%E7%82%B9%E7%9A%84%E9%9D%9E%E7%A9%BA%E5%8D%95%E9%93%BE%E8%A1%A8%E4%B8%94p%E7%BB%93%E7%82%B9%E6%97%A2%E4%B8%8D%E6%98%AF%E9%A6%96%E5%85%83%E7%BB%93%E7%82%B9%E4%B9%9F%E4%B8%8D%E6%98%AF%E5%B0%BE%E5%85%83%E7%BB%93%E7%82%B9%E8%AF%95%E4%BB%8E%E4%B8%8B%E5%88%97%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AD%94%E6%A1%88%E4%B8%AD%E9%80%89%E6%8B%A9%E5%90%88%E9%80%82%E7%9A%84%E8%AF%AD%E5%8F%A5%E5%BA%8F%E5%88%97)
答案应该为(10),(12),(8),**(11)**,(3),(14) Q指针应该移动到P指针后

**Comment by kangjianwei** [comment]
@CaiCandong 嗯，你算的是正确的。

习题2.4是因为原图存在误导性。它那个图片后面有串省略号，所以当时以为在后面还有更多结点，因此2.4.7里把最后一个结点也乘2了。现在对照2.4.6想想，从出题人的角度出发，他应该不希望最后一个结点被乘2，哎...

习题2.7.b如你所述，缺少了将Q指向待释放结点那一步。

以上问题已在Girhub中更新。
