### ISSUE TITLE
二叉树 BiTree.c 中 PrintTree() 向队列里 EnQueue(&Q, NULL); 干嘛？

### ISSUE THREAD

**Issue by dazeGitHub** [kangjianwei/Data-Structure#23]
代码片段

 DeQueue(&Q, &e);

 if (e == NULL) {
       EnQueue(&Q, NULL);            //这个放到队列里两个空元素有什么用?
       EnQueue(&Q, NULL);
} else {
      //...
}

**Comment by dazeGitHub** [comment]
而且遍历 void PrintTree(BiTree T){} 这个方法遍历二叉树完了里边的队列也没有 Destroy 掉

**Comment by kangjianwei** [comment]
@dazeGitHub 

1. 连续两次入队是因为e代表双亲结点，双亲结点为空的情形下，左右子孩子当然也为空，这一点要反应在打印图中，所以要入队。
2. 队列没有Destroy不在考虑范围内。理论上，用完的资源是应该销毁的。但是这里写的都是非后台运行的程序，而且主要是示范数据结构的逻辑，优化操作不会优先考虑。

**Comment by dazeGitHub** [comment]
呃，厉害，大佬
