### ISSUE TITLE
有电子书籍链接吗  或者这个是哪个版本的书

### ISSUE THREAD

**Issue by wuzuowuyou** [kangjianwei/Data-Structure#30]
我看网上书封面都不一样

**Comment by godvmxi** [comment]
https://github.com/HongYiMU/TheAlgorithm

**Comment by Arthurdyu** [comment]
Sorry, something went wrong. Reload?

**Comment by kangjianwei** [comment]
封面不一样没关系，基本上网上搜严蔚敏的教材，搜出来就是这本书。
