### ISSUE TITLE
HeapString.c#L248 Bug

### ISSUE THREAD

**Issue by panovr** [kangjianwei/Data-Structure#4]
It seems that there is a bug in [this line](https://github.com/kangjianwei/Data-Structure/blob/master/%E2%96%B2%E8%AF%BE%E6%9C%AC%E7%AE%97%E6%B3%95%E5%AE%9E%E7%8E%B0/%E2%96%B204%20%E4%B8%B2/02%20HeapString/HeapString.c#L248) in the `StrDelete_H` function:
```
for(i=pos-1; i+len<=(*S).length; i++)
    (*S).ch[i] = (*S).ch[i+len];
```
We can see that the max value of (i + len) is (*S).length, that means in the for loop:
`(*S).ch[i+len]` will be `(*S).ch[(*S).length]`. 
However, the last element in the String `S` is `S.ch[(*S).length-1]`.  

So the correct code should be:
```
for(i=pos-1; i+len<(*S).length; i++)
    (*S).ch[i] = (*S).ch[i+len];
```

**Comment by kangjianwei** [comment]
@panovr 嗯，你的说法是正确的！
