### ISSUE TITLE
About #include "Conversion.c"

### ISSUE THREAD

**Issue by TaiXuan91** [kangjianwei/Data-Structure#5]
个人感觉通过include直接包含.c文件的写法有点非主流。而且容易造成命名冲突，全局变量冲突之类的问题。一般来说都是将声明和宏写到.h文件里，然后include用于包含.h文件。
而.c文件之间的依赖关系由调用gcc时候的参数说明。更简易的方法是使用makefile记录这些文件之间的依赖关系。

**Comment by kangjianwei** [comment]
@TaiXuan91 直接包含.c文件是include的基本用法，优点是不需要创建特殊的编译规则。这些代码都是面向新手的，所以并没有创建到工程中，也没有手动编写编译规则，在这种限制下为了达到开箱即用的目的，故而采用了直接包含.c文件的做法。
