### ISSUE TITLE
请问怎么使用clion运行源代码？

### ISSUE THREAD

**Issue by ness001** [kangjianwei/Data-Structure#7]

**Comment by kangjianwei** [comment]
clion一般是使用gcc那一套编译体系，所以源码组织方式需要按那个套路来，依赖CMakeLists.txt中的编译规则。

**Comment by ness001** [comment]
> clion一般是使用gcc那一套编译体系，所以源码组织方式需要按那个套路来，依赖CMakeLists.txt中的编译规则。

谢谢您的回复。我对clion还不太熟悉。看到您最近更新了不同ide的readme，辛苦了，我过几天再来看看。

**Comment by kangjianwei** [comment]
已经上传了各个版本的样例，目前重构完了前两章
